// Generated by CoffeeScript 1.3.3
(function() {
  var SQLBTResource, log,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  log = require("winston");

  "Very simple helper class to expose cavia models through express. Uses express-resource.";


  SQLBTResource = (function() {

    function SQLBTResource(store, model, name) {
      this.store = store;
      this.model = model;
      this.name = name;
      this.destroy = __bind(this.destroy, this);

      this.update = __bind(this.update, this);

      this.show = __bind(this.show, this);

      this.index = __bind(this.index, this);

    }

    SQLBTResource.prototype.index = function(req, res) {
      var _this = this;
      log.info("" + this.name + ".index");
      return this.store.query(this.model, {}, function(err, result) {
        res.send(result);
        return res.end();
      });
    };

    SQLBTResource.prototype.show = function(req, res) {
      var key,
        _this = this;
      console.log(req.params);
      log.info("" + this.name + ".show\n\tkey: " + req.params[this.name]);
      key = req.params[this.name];
      return this.store.get(this.model, key, function(err, result) {
        res.send(result);
        return res.end();
      });
    };

    SQLBTResource.prototype.update = function(req, res) {
      var data,
        _this = this;
      log.info("" + this.name + ".update\n\tkey: " + req.params[this.name] + "\n\tbody: " + req.body);
      data = JSON.parse(req.body);
      data.key = req.params[this.name];
      data.kind = this.name;
      return this.store.put(data, function(err, result) {
        res.send(data);
        return res.end();
      });
    };

    SQLBTResource.prototype.destroy = function(req, res) {
      return res.send(("" + this.name + ".destroy ") + req.params[this.name]);
    };

    return SQLBTResource;

  })();

  exports.SQLBTResource = SQLBTResource;

}).call(this);
